[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
degenbets = "CwN2DiAqGTCXXVUCbRTCpD925Aq7e5VTRsLESrXr7SuL"

[programs.devnet]
degenbets = "CwN2DiAqGTCXXVUCbRTCpD925Aq7e5VTRsLESrXr7SuL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
